#!/usr/bin/env bash

## Install Drupguard project
##
## Usage: fin drupguard/install


# Abort if anything fails
set -e

#-------------------------- Settings --------------------------------

#-------------------------- END: Settings --------------------------------

#-------------------------- Helper functions --------------------------------

# Console colors
red='\033[0;31m'
green='\033[0;32m'
green_bg='\033[1;97;42m'
lavender_bg='\033[1;30;0;44m'
yellow='\033[1;33m'
NC='\033[0m'

echo-red () { echo -e "${red}$1${NC}"; }
echo-green () { echo -e "${green}$1${NC}"; }
echo-green-bg () { echo -e "${green_bg}$1${NC}"; }
echo-lavender-bg () { echo -e "${lavender_bg}$1${NC}"; }
echo-yellow () { echo -e "${yellow}$1${NC}"; }

#-------------------------- END: Helper functions --------------------------------

#-------------------------- Execution --------------------------------
cd ${PROJECT_ROOT}

echo-lavender-bg "* Generate docksal .env-local file"

cat << EOF > .env-local
APP_SECRET=$(< /dev/urandom  head -c 10 | md5sum | cut -d' ' -f1)
DATABASE_URL=mysql://user:user@db:3306/default?serverVersion=5.7
MAILER_DSN=smtp://mail:1025
PHP_BINARY=/usr/local/bin/php
COMPOSER_BINARY=/usr/local/bin/composer
HOST=drupguard.docksal.site
EOF

fin drupguard/install --install $1
#-------------------------- END: Execution --------------------------------
