#!/usr/bin/env bash

## Update Drupguard project
##
## Usage: fin drupguard/update

# Abort if anything fails
set -e

#-------------------------- Settings --------------------------------

#-------------------------- END: Settings --------------------------------

#-------------------------- Helper functions --------------------------------

# Console colors
red='\033[0;31m'
green='\033[0;32m'
green_bg='\033[1;97;42m'
lavender_bg='\033[1;30;0;44m'
yellow='\033[1;33m'
NC='\033[0m'

echo-red () { echo -e "${red}$1${NC}"; }
echo-green () { echo -e "${green}$1${NC}"; }
echo-green-bg () { echo -e "${green_bg}$1${NC}"; }
echo-lavender-bg () { echo -e "${lavender_bg}$1${NC}"; }
echo-yellow () { echo -e "${yellow}$1${NC}"; }

check_parameters() {
  while [ -n "$1" ]; do # while loop starts
    case "$1" in
      --install) install=true ;;
      -h) echo "Use 'fin help drupguard/update' instead" ;;
      *) echo "Option $1 not recognized" ;;
    esac
    shift
  done
}

#-------------------------- END: Helper functions --------------------------------

#-------------------------- Execution --------------------------------
cd ${PROJECT_ROOT}

install=false
check_parameters $@

echo-lavender-bg "* Update php packages"
fin symfony composer install

echo-lavender-bg "* Update javascript packages"
fin yarn install
fin yarn encore production

if [ "$install" = true ]
then
  echo-lavender-bg "* Application installation"
  fin symfony console drupguard:install
else
  echo-lavender-bg "* Cache clear"
  fin symfony console cache:clear
  fin symfony console doctrine:migrations:migrate
fi
#-------------------------- END: Execution --------------------------------
