# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Plugin/Source/Entity/'
            - '../src/Kernel.php'

    security.access.role_hierarchy_voter:
        class: App\Security\Voter\RoleHierarchyVoter

    App\Plugin\Service\Type\:
        resource: '../src/Plugin/Service/Type'
        tags: {name: 'app.plugin.service.type'}

    App\Service\SchedulerUpdateService:
        arguments:
            $dsn: '%env(resolve:DATABASE_URL)%'
    app_service_scheduler_update_service:
        alias: App\Service\SchedulerUpdateService

    App\EventListener\ProjectEventListener:
        arguments: [ '@app_service_scheduler_update_service', '@kernel' ]

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones