# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    drupguard.php_binary: '%env(resolve:PHP_BINARY)%'
    drupguard.composer_binary: '%env(resolve:COMPOSER_BINARY)%'
    drupguard.composer_v1_binary: '%env(resolve:COMPOSER_V1_BINARY)%'

    router.request_context.host: '%env(resolve:HOST)%'
    router.request_context.scheme: 'https'
    router.request_context.base_url: '/'
    asset.request_context.base_path: '%router.request_context.base_url%'
    asset.request_context.secure: true

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        bind:
            string $publicDir: '%kernel.project_dir%/public'
    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
    Symfony\Component\HttpFoundation\Session\Storage\Handler\PdoSessionHandler:
        arguments:
            - '%env(DATABASE_URL)%'
    app.menu_builder:
        class: App\Menu\MenuBuilder
        arguments: ["@knp_menu.factory", "@security.helper"]
        tags:
            - { name: knp_menu.menu_builder, method: createMainMenu, alias: main } # The alias is what is used to retrieve the menu
