#!/usr/bin/env bash

## Run project's update.
##
## Usage: fin drupguard-update
##

# Abort if anything fails
set -e

fin composer install
fin rebuild-assets
fin symfony console doctrine:migrations:migrate || true
fin cache-clear
