#!/usr/bin/env bash

## Run project's init.
##
## Usage: fin init
##

# Abort if anything fails
set -e

fin p reset
fin db drop default
fin db create default
fin exec 'cd /var/www && composer install'
fin rebuild-assets
fin exec 'find /var/www/migrations -name "*.php" -delete'
fin exec 'find /var/www/workspace -mindepth 1 -maxdepth 1 -type d -name "*" -exec rm -rf {} \;'
fin symfony console doctrine:schema:create -n
fin symfony console doctrine:fixtures:load -n
fin cache-clear
