#!/usr/bin/env bash

#: exec_target = cli

## Initialize/reinstall site
##
## Usage: fin init-site

# Abort if anything fails
set -e

#-------------------------- Settings --------------------------------

#-------------------------- END: Settings --------------------------------

#-------------------------- Helper functions --------------------------------

#-------------------------- END: Helper functions --------------------------------

#-------------------------- Functions --------------------------------

install_items ()
{
  echo '============'
  echo "* Install project"

}
#-------------------------- END: Functions --------------------------------

#-------------------------- Execution --------------------------------

mkdir ~/tmp
install_items
# Project initialization steps
#-------------------------- END: Execution --------------------------------
