#!/usr/bin/env bash

#: exec_target = cli

## Run project's rebuild assets.
##
## Usage: fin rebuild-assets
##

# Abort if anything fails
set -e

cd ${PROJECT_ROOT}

rm -rf public/assets
symfony console sass:build
symfony console asset-map:compile