#!/usr/bin/env bash

## Run project's update.
##
## Usage: fin update
##

# Abort if anything fails
set -e

fin composer install
fin rebuild-assets
fin symfony console doctrine:migrations:migrate
fin cache-clear
