#!/usr/bin/env bash

## Run project's symfony CLI.
##
## https://symfony.com/download
## Usage: fin init
##

# Abort if anything fails
set -e

fin composer install
fin rebuild-assets
fin symfony console doctrine:migrations:migrate
fin cache-clear
